#!/bin/sh

BRANCH=`git status | grep 'On branch' | awk '{print $NF}'`

warn() { echo "$@" >&2; }
die() { warn "$@"; exit 1; }

type_from_branch()
{
  IFS='/' read -a _DATA <<< "$BRANCH"
  echo "${_DATA[0]}"
}

task_from_branch()
{
  IFS='/' read -a _DATA <<< "$BRANCH"
  echo "${_DATA[1]}"
}

require_branch()
{
  if [ "$BRANCH" = "" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "develop" ] ; then
    die "Cannot submit $BRANCH for review, you are not on a feature branch."
  fi
}

usage()
{
	echo "usage: arcflow <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "   start     Start work on a task."
	echo "   review    Submit this branch for review."
	echo "   finish    Merge the branch into develop."
	echo "   abandon   Abandon the this branch and delete it from the repo."
}

# arcflow start Txxx
cmd_start()
{
  # must start from develop
  git checkout develop >/dev/null 2>&1

  local _TASKID="$1"; shift
  local _TASKS=`arc tasks`
  if [ "$_TASKID" = "" ] ; then
    die "No task specified\n$_TASKS";
  fi

  local _TAS=`arc tasks --owner @all | sed -E '/^'"$_TASKID"' /!d; s/ {2,}/<TAB>/g; s/^'"$_TASKID"' (.*)<TAB>(.*)<TAB>[a-zA-Z]*$/\1~\2/'`
  IFS='~' read _TITLE _TYPE <<< "$_TAS"

  if [ "$_TITLE" = "" ] ; then
    die "Task $_TASKID not found.\n$_TASKS";
  fi

  # TODO: not very flexible: Hotfix, Bug, Release Candidate, Feature
  local _FLOWTYPE=''
  if [ "$_TYPE" = "Hotfix" ]; then
    _FLOWTYPE='hotfix'
  elif [ "$_TYPE" = "Bug" ]; then
    _FLOWTYPE='feature'
  elif [ "$_TYPE" = "Feature" ]; then
    _FLOWTYPE='feature'
  elif [ "$_TYPE" = "Release Candidate" ]; then
    _FLOWTYPE='release'
  fi

  if [ "$_FLOWTYPE" = '' ]; then
    die "Task type '$_TYPE' not supported in arcflow"
  fi

  # start the hotfix/bug/release
  git flow "$_FLOWTYPE" start "$_TASKID" >/dev/null 2>&1
  _ERR=$(git branch --set-upstream-to origin/"$_FLOWTYPE"/"$_TASKID" 2>&1 >/dev/null)
  _ERR=`echo "$_ERR" | sed '/^error: the requested upstream branch .* does not exist$/!d;'`
  #if branch failed, git push, else git pull --rebase
  if [ "$_ERR" != "" ] ; then
    echo "Starting $_TYPE $_TASKID - $_TITLE"
    git push --set-upstream origin "$_FLOWTYPE"/"$_TASKID" >/dev/null 2>&1
  else
    echo "Resuming $_TYPE $_TASKID - $_TITLE"
    git pull --rebase >/dev/null 2>&1
  fi

  echo "Now, start committing to your $_TYPE. When done, use:\n\n      arcflow review\n"
}

# arcflow review
cmd_review()
{
  require_branch
  echo "Submitting $BRANCH for review."
  arc diff develop
}

# arcflow finish
cmd_finish()
{
  require_branch
  local _TYPE=`type_from_branch`
  local _TASK=`task_from_branch`
  git flow "$_TYPE" finish "$_TASK"
}

cmd_abandon()
{
  require_branch
  read -p "Are you sure you wish to abandon $BRANCH [y/N]? " -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    delete_branch
  fi
}

delete_branch()
{
  require_branch
  git checkout develop
  git branch -d "$BRANCH"
  git push origin :"$BRANCH"
}

SUBCOMMAND="$1"; shift
if [ "" = "$SUBCOMMAND" ]; then
  usage
elif ! type "cmd_$SUBCOMMAND" >/dev/null 2>&1; then
	die "Unknown subcommand: '$SUBCOMMAND'"
else
  cmd_$SUBCOMMAND "$@"
fi
